### ISSUE TITLE
Suggested additions to the ESP32 Version

### ISSUE THREAD

**Issue by coopzone-dc** [MockbaTheBorg/RunCPM#119]
Hello,
I have cloned this repo, and modified the ESP32 part of it to use the FABGL VGA drivers. You end up with a stand alone useable computer, vga screeb+keyboard.

I was to see what you think, and if you like it (after a bit of tidy up) would you add these changes to a development branch perhaps?

See https://github.com/coopzone-dc/RunCPM

Derek

**Comment by MockbaTheBorg** [comment]
Hi @coopzone-dc,

This is a really cool project.
I will not join it onto the main code though, because my idea is to only put on the main code things that are as common as possible throughout all the platforms. So I keep it minimalistic.
This one is very ESP32 specific, so it makes sense to be your separate project.
I have added though a link to your page from the RunCPM Readme references.
Again, congratulations on the great project.

Cheers,
Marcelo.
