### ISSUE TITLE
NZCOM

### ISSUE THREAD

**Issue by CPMArchives** [MockbaTheBorg/RunCPM#148]
I noticed NZCOM.CCP in A.ZIP. Is this an NZCOM CCP binary? If so, I've failed to load it with any of the stock RunCPM.* binaries. Is this doable?

Alternatively, ZCPR 3.3 and 3.4 are major upgrades to 3.0, adding Z3ENV support which most of the Z-System utilities need to run.

v4.0 is also available. 

Are any of those possible?

**Comment by MockbaTheBorg** [comment]
I do not have NZCOM.CCP distributed as part of A.ZIP. (see picture)
Nor I have it on the CCP folder. This might be some local file of yours.

ZCPR 3.3 and 3.4 MIGHT be able to run. I remember some CCP had direct access to disk tracks and sectors, and were therefore unable to run on RunCPM due to no underlying hardware emulation.
If ZCPR 3.3 and 3.4 rely solely on BDOS/BIOS call except the Track/Sector ones, then there's a chance they can be used.

Cheers,
Marcelo.
