### ISSUE TITLE
Transverse (copy/execute) between slices

### ISSUE THREAD

**Issue by kenmartin-unix** [MockbaTheBorg/RunCPM#172]
Working great!!! Good job.

Got a question example drive C2 has a C source if I try and execute A0:TE.com
it says no file. However if I go to A0 I can see TE.com.

How do I transverse (move stuff) between C1 C2 and A0 and A1. Then Execute it?

Sorry for so many questions. The CP/M manual I have does not cover slices.

Appreciate it Ken.

**Comment by MockbaTheBorg** [comment]
Copying files among different user areas (A0, C2, B1, etc) was always a problem with CP/M.

When using PIP:
Gn = Get file from user area "n"
e.g., PIP A: = CONFIG.COM [G0]
will copy the file CONFIG.COM from user area 0 into the current user area
This page goes deep into PIP: http://www.shaels.net/index.php/cpm80-22-documents/using-cpm/6-pip-utility

If you are using RunCPM with the internal (native) CCP instead of the standard DR CCP, then TE.COM would be searched locally, on C2:, if not found, would be searched on C0: and, if still not found, on A0:
So, if you are on C2: and using the internal CCP you can just type:
TE HELLO.C

Before using the internal (or any other) CCP, I recommend a detailed reading of the RunCPM readme file (the GitHub front page) as it contains all the currently known hints and 'gotchas' ot RunCPM.

Looks like there was a 3rd party app called COPY.COM indeed. I have found some discussion here: https://forum.vcfed.org/index.php?threads/cpm-ish-how-to-copy-to-another-user-area.77714/

Now, copying among user areas to edit, then back to compile becomes counter-productive really quick. I recommend to just use the internal CCP or any other of the CCP provided than CCP_DR.

Have fun!
